# Numpy

## Array types and conversions between types

In [101]:
import numpy as np

In [103]:
integers=np.array([10,20,30,40,50])
print(integers)

[10 20 30 40 50]


In [105]:
integers[0]

10

In [107]:
integers[0]=20
integers

array([20, 20, 30, 40, 50])

In [109]:
integers[0]=21.5
integers

array([21, 20, 30, 40, 50])

In [111]:
integers.dtype

dtype('int32')

In [113]:
smallerIntegers=np.array(integers,dtype=np.int8)
smallerIntegers

array([21, 20, 30, 40, 50], dtype=int8)

In [115]:
integers.nbytes

20

In [117]:
smallerIntegers.nbytes

5

In [119]:
overflow=np.array([127,128,129],dtype=np.int16)
print(overflow)

[127 128 129]


In [121]:
overflow = np.array([127, 128, 129]).astype(np.int8)
overflow


array([ 127, -128, -127], dtype=int8)

In [123]:
floats=np.array([1.2,5.6,7.8,9.8])
floats

array([1.2, 5.6, 7.8, 9.8])

In [125]:
floats.dtype

dtype('float64')

In [127]:
array1 = [ 'WA' , 24, 'CA', 'NH', 564]
array2 = np.array(array1)
print(array2)

['WA' '24' 'CA' 'NH' '564']


## multidimensionally array

In [130]:
nums=np.array([[1,2,3,4,5,],[6,7,8,9,10]])
nums

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [132]:
nums[0,0]

1

In [134]:
nums[1,4]

10

In [136]:
nums.ndim

2

In [138]:
multi_arr=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
multi_arr

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [140]:
multi_arr[1,0,2]

9

## creating arrays from lists and other python structure

In [143]:
first_list=[1,2,3,4,5,6,7,8,9,10]
first_list

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [145]:
first_array=np.array(first_list)
first_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [147]:
second_list=[1,2,3,-1.23,50,128990.90,7.54]
second_array=np.array(second_list)

In [149]:
second_array

array([ 1.000000e+00,  2.000000e+00,  3.000000e+00, -1.230000e+00,
        5.000000e+01,  1.289909e+05,  7.540000e+00])

In [151]:
second_array.dtype

dtype('float64')

In [153]:
third_list=["Ann","11111111","Peter","908"]
third_list
        

['Ann', '11111111', 'Peter', '908']

In [155]:
third_array=np.array(third_list)
third_array

array(['Ann', '11111111', 'Peter', '908'], dtype='<U8')

In [157]:
first_tuple=(5,10,15,20,25,30)
array_from_tuple=np.array(first_tuple)
array_from_tuple

array([ 5, 10, 15, 20, 25, 30])

In [159]:
array_from_tuple.dtype

dtype('int32')

In [161]:
multi_dim_list=([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
arr_from_multi_dim_list=np.array(multi_dim_list)
arr_from_multi_dim_list

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

## intrisic Numpy array creation

In [164]:
integers_array=np.arange(10)
integers_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [166]:
integers_second_array=np.arange(100,130)
integers_second_array

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112,
       113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125,
       126, 127, 128, 129])

In [168]:
integers_third_array=np.arange(100,151,2)
integers_third_array

array([100, 102, 104, 106, 108, 110, 112, 114, 116, 118, 120, 122, 124,
       126, 128, 130, 132, 134, 136, 138, 140, 142, 144, 146, 148, 150])

In [170]:
first_floats_arr=np.linspace(10,20)
first_floats_arr

array([10.        , 10.20408163, 10.40816327, 10.6122449 , 10.81632653,
       11.02040816, 11.2244898 , 11.42857143, 11.63265306, 11.83673469,
       12.04081633, 12.24489796, 12.44897959, 12.65306122, 12.85714286,
       13.06122449, 13.26530612, 13.46938776, 13.67346939, 13.87755102,
       14.08163265, 14.28571429, 14.48979592, 14.69387755, 14.89795918,
       15.10204082, 15.30612245, 15.51020408, 15.71428571, 15.91836735,
       16.12244898, 16.32653061, 16.53061224, 16.73469388, 16.93877551,
       17.14285714, 17.34693878, 17.55102041, 17.75510204, 17.95918367,
       18.16326531, 18.36734694, 18.57142857, 18.7755102 , 18.97959184,
       19.18367347, 19.3877551 , 19.59183673, 19.79591837, 20.        ])

In [172]:
second_floats_arr=np.linspace(10,20,5)
second_floats_arr

array([10. , 12.5, 15. , 17.5, 20. ])

In [174]:
first_rand_arr=np.random.rand(10)
first_rand_arr

array([0.11952568, 0.38796834, 0.69531123, 0.75248774, 0.4638671 ,
       0.32738027, 0.20623931, 0.57396103, 0.91018086, 0.16756134])

In [176]:
second_rand_arr=np.random.rand(4,4)
second_rand_arr

array([[0.07609928, 0.47891887, 0.19879849, 0.17729402],
       [0.69079253, 0.09883551, 0.73128633, 0.90873487],
       [0.65373761, 0.87719744, 0.92784005, 0.54179195],
       [0.16740373, 0.48997893, 0.2393591 , 0.99971447]])

In [178]:
third_rand_arr=np.random.randint(0,100,20)
third_rand_arr

array([57, 14, 26, 90, 65, 37, 80, 19, 86, 90, 74,  0, 83, 72, 42,  9, 83,
       91, 42, 15])

## Creating arrays filled with constant values

In [181]:
#all zeros
#1 d array
first_z_array=np.zeros(5)
first_z_array

array([0., 0., 0., 0., 0.])

In [183]:
#2d array (4 rows and 5 columns)
second_z_array=np.zeros((4,5))
second_z_array

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [185]:
#all 1
#1 d array
first_ones_array=np.ones(6)
first_ones_array

array([1., 1., 1., 1., 1., 1.])

In [187]:
#2d array
second_ones_array=np.ones((7,8))
second_ones_array

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

In [189]:
third_ones_array=np.ones((4,5),dtype=int)
third_ones_array

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [191]:
# fill function is used to create one-dimensional array
#full function used to create both 1-dimensional and 2-dimensional arrays
#and fill function is used t fill an already existing gandy array with similar array
first_fill_array=np.empty(10,dtype=int)
first_fill_array.fill(12)
first_fill_array

array([12, 12, 12, 12, 12, 12, 12, 12, 12, 12])

In [193]:
first_full_array=np.full(5,10)
first_full_array

array([10, 10, 10, 10, 10])

In [195]:
second_full_array=np.full((4,5),8)
second_full_array

array([[8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8]])

##  Finding the shape and size of an array

In [198]:
first_arr=np.arange(20)
first_arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [200]:
second_arr=np.linspace((1,2),(10,20),10)
second_arr

array([[ 1.,  2.],
       [ 2.,  4.],
       [ 3.,  6.],
       [ 4.,  8.],
       [ 5., 10.],
       [ 6., 12.],
       [ 7., 14.],
       [ 8., 16.],
       [ 9., 18.],
       [10., 20.]])

In [202]:
third_arr=np.full((2,2,2),10)
third_arr

array([[[10, 10],
        [10, 10]],

       [[10, 10],
        [10, 10]]])

In [204]:
#number of elements in each dimension
np.shape(first_arr)

(20,)

In [206]:
#10=number of rows,2 =number of columns
np.shape(second_arr)

(10, 2)

In [208]:
np.shape(third_arr)

(2, 2, 2)

In [210]:
np.size(first_arr)

20

In [149]:
np.size(second_arr)

20

In [151]:
np.size(third_arr)


8

#### multi_DArray[1, 0, 2]
Let’s break it into parts:

1 → second block

0 → first row inside that block

2 → third element in that row (indexing starts at 0)

In [156]:
multi_DArray = np.array( [ [ [1,2,3,4,5], 
                                                 [5,4,3,2,1] ],
                                              [ [6,7,8,9,10], 
                                                [10,9,8,7,6] ] ] )
multi_DArray[1, 0, 2]

8

## Adding, removing and sorting elements

In [165]:
first_arr=np.array([1, 2, 3, 5])
first_arr

array([1, 2, 3, 5])

In [167]:
new_first_arr=np.insert(first_arr,3,4)
new_first_arr

array([1, 2, 3, 4, 5])

In [169]:
second_arr=np.array([1,2,3,4])
second_arr

array([1, 2, 3, 4])

In [171]:
new_second_arr=np.append(second_arr,5)
new_second_arr

array([1, 2, 3, 4, 5])

In [173]:
third_arr=np.array([1,2,3,4,5])
third_arr

array([1, 2, 3, 4, 5])

In [175]:
del_arr=np.delete(third_arr,4)
del_arr

array([1, 2, 3, 4])

In [177]:
integers_arr=np.random.randint(0,20,20)
integers_arr

array([19, 19, 13,  6,  2,  7,  0,  9,  0, 12, 13,  7, 19, 15, 12, 11, 14,
        5,  5, 10])

In [179]:
print(np.sort(integers_arr))

[ 0  0  2  5  5  6  7  7  9 10 11 12 12 13 13 14 15 19 19 19]


In [181]:
integers_2dim_arr=np.array([[3, 2, 5,7, 4], [5, 0, 8,3, 1]])
integers_2dim_arr

array([[3, 2, 5, 7, 4],
       [5, 0, 8, 3, 1]])

In [183]:
print(np.sort(integers_2dim_arr))

[[2 3 4 5 7]
 [0 1 3 5 8]]


In [185]:
colors=np.array(['orange','green','yellow','white','black','pink','blue','red'])
colors

array(['orange', 'green', 'yellow', 'white', 'black', 'pink', 'blue',
       'red'], dtype='<U6')

In [187]:
print(np.sort(colors))

['black' 'blue' 'green' 'orange' 'pink' 'red' 'white' 'yellow']


## Copies and views

In [190]:
students_ids_number=np.array([1111,1212,1313,1414,1515,1616,1717,1818])
students_ids_number

array([1111, 1212, 1313, 1414, 1515, 1616, 1717, 1818])

In [192]:
students_ids_number_reg=students_ids_number
print("id of students_ids_number",id(students_ids_number))
print("id of students_ids_number_reg",id(students_ids_number_reg))

id of students_ids_number 2286770295920
id of students_ids_number_reg 2286770295920


In [194]:
students_ids_number_reg[1]=2222
print(students_ids_number)
print(students_ids_number_reg)

[1111 2222 1313 1414 1515 1616 1717 1818]
[1111 2222 1313 1414 1515 1616 1717 1818]


In [198]:
students_ids_number_cp=students_ids_number.copy()
print(students_ids_number_cp)

[1111 2222 1313 1414 1515 1616 1717 1818]


In [200]:
print(students_ids_number_cp==students_ids_number)

[ True  True  True  True  True  True  True  True]


In [202]:
print ("id of students_ids_number",id(students_ids_number))
print("id of students_ids_number_cp",id(students_ids_number_cp))

id of students_ids_number 2286770295920
id of students_ids_number_cp 2286770295152


In [204]:
students_ids_number[0]=1000
print ("original: ", students_ids_number)
print("copy: ",students_ids_number_cp)

original:  [1000 2222 1313 1414 1515 1616 1717 1818]
copy:  [1111 2222 1313 1414 1515 1616 1717 1818]


In [206]:
students_ids_number_v=students_ids_number.view()

In [208]:
students_ids_number_v[0]=2000
print("original: ", students_ids_number)
print("view:",students_ids_number_v)

original:  [2000 2222 1313 1414 1515 1616 1717 1818]
view: [2000 2222 1313 1414 1515 1616 1717 1818]


In [210]:
print(students_ids_number_cp.base)
print(students_ids_number_v.base)

None
[2000 2222 1313 1414 1515 1616 1717 1818]


## Reshaping arrays

In [213]:
first_arr=np.arange(1,13)
first_arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [215]:
second_arr=np.reshape(first_arr,(3,4))
second_arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [217]:
third_arr=np.reshape(first_arr,(6,2))
third_arr

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [219]:
fourth_arr=np.reshape(first_arr,(4,4))

ValueError: cannot reshape array of size 12 into shape (4,4)

In [221]:
fifth_arr=np.reshape(first_arr,(3,2,2))
print(fifth_arr)
print("Dimensions of fifth_arr is ",fifth_arr.ndim)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]
Dimensions of fifth_arr is  3


In [223]:
sixth_arr=np.array([[1,2],[3,4],[5,6]])
sixth_arr

array([[1, 2],
       [3, 4],
       [5, 6]])

In [225]:
seventh_arr_flat=np.reshape(sixth_arr,-1)
seventh_arr_flat

array([1, 2, 3, 4, 5, 6])

In [227]:
eighth_arr_flat=sixth_arr.flatten()
print("eighth_arr_flat:",eighth_arr_flat)
ninth_arr_rav=sixth_arr.ravel()
print("ninth_arr_rav:",ninth_arr_rav)

eighth_arr_flat: [1 2 3 4 5 6]
ninth_arr_rav: [1 2 3 4 5 6]


In [229]:
eighth_arr_flat[0]=100

In [231]:
eighth_arr_flat[0]=100

In [233]:
print("eighth_arr_flat:",eighth_arr_flat)
print("ninth_arr_rav:",ninth_arr_rav)
print("sixth_arr:",sixth_arr)

eighth_arr_flat: [100   2   3   4   5   6]
ninth_arr_rav: [1 2 3 4 5 6]
sixth_arr: [[1 2]
 [3 4]
 [5 6]]


## Indexing and slicing

In [236]:
twodim_arr=np.reshape(np.arange(12),(3,4))
twodim_arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [238]:
twodim_arr[1,1]

5

In [240]:
twodim_arr[1]

array([4, 5, 6, 7])

In [242]:
threedim_arr=np.reshape(np.arange(3*4*5),(3,4,5))
threedim_arr

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39]],

       [[40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59]]])

In [244]:
threedim_arr[0,2,3]

13

In [246]:
threedim_arr[2,-1,-1]

59

In [248]:
onedim_arr=np.arange(10)
onedim_arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [250]:
onedim_arr[2:6]

array([2, 3, 4, 5])

In [252]:
onedim_arr[:5]

array([0, 1, 2, 3, 4])

In [254]:
onedim_arr[-3:]

array([7, 8, 9])

In [256]:
onedim_arr[::2]

array([0, 2, 4, 6, 8])

In [258]:
twodim_arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [260]:
twodim_arr[1:,1:]

array([[ 5,  6,  7],
       [ 9, 10, 11]])

In [262]:
twodim_arr[1,:]

array([4, 5, 6, 7])

In [264]:
twodim_arr[:,2]

array([ 2,  6, 10])

## Joining and splitting ararys

In [267]:
first_arr=np.arange(1,11)
second_arr=np.arange(11,21)
print("first_arr",first_arr)
print("second_arr",second_arr)

first_arr [ 1  2  3  4  5  6  7  8  9 10]
second_arr [11 12 13 14 15 16 17 18 19 20]


In [269]:
con_arr=np.concatenate((first_arr,second_arr))
con_arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [271]:
third_2darr=np.array([[1,2,3,4,5], [6,7,8,9,10]])
third_2darr


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [273]:
fourth_2darr=np.array([[11,12,13,14,15], [16,17,18,19,20]])
fourth_2darr

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [275]:
con2d_arr = np.concatenate((third_2darr,fourth_2darr),axis=1)
con2d_arr

array([[ 1,  2,  3,  4,  5, 11, 12, 13, 14, 15],
       [ 6,  7,  8,  9, 10, 16, 17, 18, 19, 20]])

In [277]:
st_arr = np.stack((first_arr,second_arr))
st_arr 

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20]])

In [279]:
hst_arr=np.hstack((first_arr,second_arr))
hst_arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [281]:
vst_arr=np.vstack((first_arr,second_arr))
vst_arr

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20]])

In [283]:
fifth_arr=np.arange(1,13)
fifth_arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [285]:
sp_arr=np.array_split(fifth_arr,4)
sp_arr

[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9]), array([10, 11, 12])]

In [287]:
print(sp_arr[1])

[4 5 6]


In [289]:
sp_arr=np.array_split(fifth_arr,8)
sp_arr

[array([1, 2]),
 array([3, 4]),
 array([5, 6]),
 array([7, 8]),
 array([9]),
 array([10]),
 array([11]),
 array([12])]

In [291]:
np.hsplit(third_2darr,5)


[array([[1],
        [6]]),
 array([[2],
        [7]]),
 array([[3],
        [8]]),
 array([[4],
        [9]]),
 array([[ 5],
        [10]])]

In [295]:
vs_arr=np.vsplit(third_2darr,2)
vs_arr

[array([[1, 2, 3, 4, 5]]), array([[ 6,  7,  8,  9, 10]])]

## Arithmetic operations

In [298]:
a=np.arange(1,11)
b=np.arange(21,31)
print("a",a)
print("b",b)

a [ 1  2  3  4  5  6  7  8  9 10]
b [21 22 23 24 25 26 27 28 29 30]


In [300]:
a+b

array([22, 24, 26, 28, 30, 32, 34, 36, 38, 40])

In [302]:
b-a

array([20, 20, 20, 20, 20, 20, 20, 20, 20, 20])

In [304]:
a*b

array([ 21,  44,  69,  96, 125, 156, 189, 224, 261, 300])

In [306]:
b/a

array([21.        , 11.        ,  7.66666667,  6.        ,  5.        ,
        4.33333333,  3.85714286,  3.5       ,  3.22222222,  3.        ])

In [308]:
c=np.arange(2,12)
print("c",c)

c [ 2  3  4  5  6  7  8  9 10 11]


In [310]:
a**c

array([         1,          8,         81,       1024,      15625,
           279936,    5764801,  134217728, -808182895, 1215752192])

In [314]:
a*2

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [316]:
np.add(a,b)

array([22, 24, 26, 28, 30, 32, 34, 36, 38, 40])

In [318]:
np.subtract(b,a)

array([20, 20, 20, 20, 20, 20, 20, 20, 20, 20])

In [320]:
np.multiply(a,b)

array([ 21,  44,  69,  96, 125, 156, 189, 224, 261, 300])

In [322]:
np.divide(b,a)

array([21.        , 11.        ,  7.66666667,  6.        ,  5.        ,
        4.33333333,  3.85714286,  3.5       ,  3.22222222,  3.        ])

In [324]:
np.mod(b,a)

array([0, 0, 2, 0, 0, 2, 6, 4, 2, 0])

In [326]:
np.power(a,c)

array([         1,          8,         81,       1024,      15625,
           279936,    5764801,  134217728, -808182895, 1215752192])

In [328]:
np.sqrt(a)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766])

## Broadcasting

In [4]:

a=np.arange(1,10).reshape(3,3)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
b=np.arange(1,4)
b

array([1, 2, 3])

In [8]:
a+b

array([[ 2,  4,  6],
       [ 5,  7,  9],
       [ 8, 10, 12]])

In [10]:
c=np.arange(1,3)
c

array([1, 2])

In [12]:
a+c

ValueError: operands could not be broadcast together with shapes (3,3) (2,) 

In [14]:
d=np.arange(24).reshape(2,3,4)
d

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [16]:
e=np.arange(4)
e

array([0, 1, 2, 3])

In [18]:
d-e

array([[[ 0,  0,  0,  0],
        [ 4,  4,  4,  4],
        [ 8,  8,  8,  8]],

       [[12, 12, 12, 12],
        [16, 16, 16, 16],
        [20, 20, 20, 20]]])

## Aggregate functions

In [8]:
first_arr=np.arange(10,110,10)
first_arr

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [10]:
second_arr=np.arange(10,100,10).reshape(3,3)
second_arr

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [12]:
third_arr=np.arange(10,110,10).reshape(2,5)
third_arr

array([[ 10,  20,  30,  40,  50],
       [ 60,  70,  80,  90, 100]])

In [14]:
first_arr.sum()

550

In [16]:
second_arr.sum()

450

In [18]:
third_arr.sum()

550

In [20]:
second_arr.sum(axis=0)

array([120, 150, 180])

In [22]:
second_arr.sum(axis=1)

array([ 60, 150, 240])

In [24]:
first_arr.prod()

1704722432

In [26]:
second_arr.prod()

-1786839040

In [28]:
third_arr.prod()

1704722432

In [30]:
third_arr.prod(axis=0)

array([ 600, 1400, 2400, 3600, 5000])

In [32]:
np.average(first_arr)

55.0

In [34]:
np.average(second_arr)

50.0

In [36]:
np.average(third_arr)

55.0

In [38]:
np.min(first_arr)

10

In [40]:
np.max(first_arr)

100

In [42]:
np.mean(first_arr)

55.0

In [44]:
np.std(first_arr)

28.722813232690143

## How to get unique items and counts

In [49]:
first_arr=np.array([1,2,3,4,5,6,1,2,7,2,1,10,7,8])

In [51]:
np.unique(first_arr)

array([ 1,  2,  3,  4,  5,  6,  7,  8, 10])

In [53]:
second_arr=np.array([[1, 1, 2,1] ,[ 3, 1, 2,1] , [1, 1, 2, 1], [ 7, 1, 1, 1]])
second_arr

array([[1, 1, 2, 1],
       [3, 1, 2, 1],
       [1, 1, 2, 1],
       [7, 1, 1, 1]])

In [55]:
np.unique(second_arr)

array([1, 2, 3, 7])

In [57]:
np.unique(second_arr,axis=0)

array([[1, 1, 2, 1],
       [3, 1, 2, 1],
       [7, 1, 1, 1]])

In [59]:
np.unique(second_arr,axis=1)

array([[1, 1, 2],
       [1, 3, 2],
       [1, 1, 2],
       [1, 7, 1]])

In [61]:
np.unique(first_arr,return_index= True)

(array([ 1,  2,  3,  4,  5,  6,  7,  8, 10]),
 array([ 0,  1,  2,  3,  4,  5,  8, 13, 11], dtype=int64))

In [63]:
np.unique(second_arr,return_counts=True)

(array([1, 2, 3, 7]), array([11,  3,  1,  1], dtype=int64))

## Transpose like operations

In [66]:
first_2dimarr=np.arange(12).reshape((3,4))
first_2dimarr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [68]:
np.transpose(first_2dimarr)

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [70]:
second_2dimarr=np.arange(6).reshape(3,2)
second_2dimarr

array([[0, 1],
       [2, 3],
       [4, 5]])

In [72]:
np.transpose(second_2dimarr,(1,0))

array([[0, 2, 4],
       [1, 3, 5]])

In [74]:
first_3dimarr=np.arange(24).reshape(2,3,4)
first_3dimarr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [76]:
np.moveaxis(first_3dimarr,0,-1)

array([[[ 0, 12],
        [ 1, 13],
        [ 2, 14],
        [ 3, 15]],

       [[ 4, 16],
        [ 5, 17],
        [ 6, 18],
        [ 7, 19]],

       [[ 8, 20],
        [ 9, 21],
        [10, 22],
        [11, 23]]])

In [78]:
np.swapaxes(first_3dimarr,0,2)

array([[[ 0, 12],
        [ 4, 16],
        [ 8, 20]],

       [[ 1, 13],
        [ 5, 17],
        [ 9, 21]],

       [[ 2, 14],
        [ 6, 18],
        [10, 22]],

       [[ 3, 15],
        [ 7, 19],
        [11, 23]]])

## Reversing an array

In [81]:
arr_1dim=[10,1,9,2,8,3,7,4,6,5]
arr_1dim

[10, 1, 9, 2, 8, 3, 7, 4, 6, 5]

In [83]:
arr_1dim[::-1]

[5, 6, 4, 7, 3, 8, 2, 9, 1, 10]

In [85]:
np.flip(arr_1dim)

array([ 5,  6,  4,  7,  3,  8,  2,  9,  1, 10])

In [87]:
arr_2dim=np.arange(9).reshape(3,3)
arr_2dim

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [89]:
np.flip(arr_2dim)

array([[8, 7, 6],
       [5, 4, 3],
       [2, 1, 0]])

In [91]:
np.flip(arr_2dim,1)

array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])

In [93]:
arr_3dim=np.arange(24).reshape(2,3,4)
arr_3dim

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [95]:
np.flip(arr_3dim,1)

array([[[ 8,  9, 10, 11],
        [ 4,  5,  6,  7],
        [ 0,  1,  2,  3]],

       [[20, 21, 22, 23],
        [16, 17, 18, 19],
        [12, 13, 14, 15]]])

In [97]:
np.flip(arr_3dim,2)

array([[[ 3,  2,  1,  0],
        [ 7,  6,  5,  4],
        [11, 10,  9,  8]],

       [[15, 14, 13, 12],
        [19, 18, 17, 16],
        [23, 22, 21, 20]]])